<?php
/**
 * Created by PhpStorm.
 * User: artur
 * Date: 10.01.2018
 * Time: 09:47
 */

namespace Arrow\Models;

use function file_exists;
use Symfony\Component\Routing\Loader\AnnotationDirectoryLoader;
use Symfony\Component\Routing\RouteCollection;
use const ARROW_DOCUMENTS_ROOT;
use function is_array;

class AnnotationsDirectoriesLoader extends AnnotationDirectoryLoader
{
    public function load($path, $type = null)
    {

        //ExceptionHandler::getDefault()->clearOutput = false;

        if (is_array($path)) {
            $collection = new RouteCollection();
            foreach ($path as $_path) {
                //print $_path."<br />";
                //if Controller dir exist in package
                if(file_exists($_path)) {
                    $collection->addCollection(parent::load($_path, $type));
                }
            }

            return $collection;
        }

        return parent::load($path, $type); // TODO: Change the autogenerated stub
    }


}
