<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'arrow\\package\\communication\\contactform' => '/ContactForm.php',
                'commimapclient' => '/messages/CommIMAPClient.php',
                'comminternalmessage' => '/internal/CommInternalMessage.php',
                'commmailbox' => '/messages/CommMailbox.php',
                'commmailboxmessage' => '/messages/CommMailboxMessage.php',
                'commmailerapi' => '/mailer/CommMailerAPI.php',
                'commmessage' => '/messages/CommMessage.php',
                'commmessageattachments' => '/messages/CommMessageAttachments.php',
                'commmessagemanager' => '/messages/CommMessageManager.php',
                'commmessageparser' => '/messages/CommMessageParser.php',
                'commnewsletteradressee' => '/newsletter/CommNewsletterAdressee.php',
                'commnewslettercampaign' => '/newsletter/CommNewsletterCampaign.php',
                'commnewslettercampaigngroup' => '/newsletter/CommNewsletterCampaignGroup.php',
                'commnewslettergroup' => '/newsletter/CommNewsletterGroup.php',
                'commnewslettergroupsubscriber' => '/newsletter/CommNewsletterGroupSubscriber.php',
                'commnewsletterqueue' => '/newsletter/CommNewsletterQueue.php',
                'mail' => '/mailer/Mail.php',
                'mailtemplate' => '/mailer/MailTemplate.php',
                'phpmailer' => '/mailer/mailer/phpmailer.php',
                'phpmailerexception' => '/mailer/mailer/phpmailer.php',
                'pop3' => '/mailer/mailer/class.pop3.php',
                'smtp' => '/mailer/mailer/class.smtp.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd